### PR TITLE
Validation for image filenames, count, and sequence

### LINKED ISSUE #12: error if apparent skip in image file sequence
note that this could be because file is mis-named or has the wrong sequence & user should check the other warnings

### PR DESCRIPTION
**Pull request by grosscol**
Adds an image module to the validation modules.
Separates out count, filename, and sequence as separate validations.

Closes #12 and then some.

### CODE REVIEW

**Comment by grosscol** [comment]
The count validation could do more.  It doesn't return an error when there are no image files.  I was unsure if all three validations should halt on this condition.

If all image validations should halt on the lack of image filenames, the convenience method for creating a no_image_files error should be extracted to the module.  However, that creates difficulty with assigning the correct value the `validation` key of the message automatically.  Currently, that is a hand crafted symbol that resembles the package and class.

File: lib/ht_sip_validator/validation/image/count.rb [hunk 1]
```diff
@@ -0,0 +1,28 @@
+# frozen_string_literal: true
+
+module HathiTrust::Validation::Image
+  class Count < HathiTrust::Validation::Base
+
+    def perform_validation
+      image_files = HathiTrust::Validation::Image.image_files(@sip.files)
+      
+      if image_files.count != text_files.count
```
Comment (aelkiss) [inline lib/ht_sip_validator/validation/image/count.rb]: We probably won't want to enable this validator by default - while some institutions might want to check this is the case, in general, it's OK to be missing OCR for some images. (It would NOT be OK to have OCR with no corresponding image, though!)

File: spec/validation/image/sequence_spec.rb [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+      end
+
+      before(:each) { allow(mocked_sip).to receive(:files).and_return(file_list) }
+
+      it_behaves_like "a validation with an invalid package"
+
+      it "emits an error for each gap in the file sequence." do
+        returned_messages = validation.validate
+        expect(returned_messages.count).to eq(2)
+        expect(returned_messages.all?(&:error?)).to be true
```
Comment (aelkiss) [inline spec/validation/image/sequence_spec.rb]: We should also have a spec to ensure that the error message actually refers to the missing file.

**Comment by aelkiss** [comment]
Re: error for no image files - I would make this a separate validator and then (when we implement it via #5) make it so the image filename checks don't run at all if there are no image files.

File: lib/ht_sip_validator/validation/image/count.rb (hunk 1 above)
Comment (grosscol) [inline lib/ht_sip_validator/validation/image/count.rb]: In that case, do we want to:
- Error on images count is less than text count.  
- Warn when images count is greater than text count.

File: spec/validation/image/sequence_spec.rb (hunk 2 above)
Comment (grosscol) [inline spec/validation/image/sequence_spec.rb]: Appropriate message spec.  Will do.

File: lib/ht_sip_validator/validation/image/filenames.rb [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    def no_images_error
+        create_error(
+          validation: :image_sequence,
+          human_message: "No image filenames recognized.",
+          extras: { image_count: 0 }
+        )
+    end
+
+    def is_valid_filename?(filename)
+      File.basename(filename) =~ /^\d+$/
```
Comment (grosscol) [inline lib/ht_sip_validator/validation/image/filenames.rb]: Crap.  I've coded myself into a corner.  In order to even be in the list of image_files, the extension is checked against a constant defined at the module level.
```HathiTrust::Validation::Image::IMG_FILE_EXTENSIONS = [".jp2", ".tif", ".png"].freeze```
However, that means if the extensions are checked again elsewhere, both of those checks need to be kept in sync.  Maybe it's just a bad function name.  Perhaps ``is_basename_valid?``` would be more fitting.

I assumed png where in there since they're specified in the HathiTrust Data API.  I'll remove png from that array.

File: lib/ht_sip_validator/validation/image/count.rb (hunk 1 above)
Comment (aelkiss) [inline lib/ht_sip_validator/validation/image/count.rb]: Sounds good to me. Some institutions may want to have a way to disable the warning for image count > text count, but we can worry about that later.

**Comment by grosscol** [comment]
I'll remove the specific error.  However, the logic to handle no images still needs to be present in order to avoid a runtime error.  "What happens when there are no images" still needs to be in the specs.  It also means the spec for this validation will read like, "when there are no images, validation behaves like a validation with a valid package."  I think that would be a mistake as it doesn't align with the specification for the packages.

I imagine the no-image-files case would be handled by a validation that checks for the presence of required files.  "A valid package has at least one image file" or something of that sort.  At that point, it might be useful to implement the image_files function in the sip package class.  Otherwise we'd have multiple modules that require the same function, and might diverge in their implementation.

**Comment by aelkiss** [comment]
Let's discuss in our meeting.

**Comment by grosscol** [comment]
Pursuant to #68, this PR will have to be refactored along with the other current Validations to be Validators while the existing Validator becomes ValidationRunner.

Do we want to merge this and then refactor, or refactor the names, then rebase and refactor this PR?

**Comment by aelkiss** [comment]
I'll merge it now and work on refactoring today.
